# Generated by Django 2.2 on 2019-04-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=50)),
                ('profesion', models.CharField(choices=[('Fotografo', 'Fotografo'), ('Programador', 'Programador'), ('Profesor particular', 'Profesor particular')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('telefono1', models.IntegerField()),
            ],
        ),
    ]
