# Generated by Django 2.2 on 2019-04-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagweb', '0002_auto_20190429_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='fotoportfolio',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
