# Generated by Django 2.2 on 2019-04-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagweb', '0003_freelancer_fotoportfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
