# Generated by Django 2.2 on 2019-04-30 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagweb', '0005_profesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='profesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagweb.Profesion'),
        ),
    ]
