# Generated by Django 2.2 on 2019-04-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagweb', '0006_auto_20190430_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='profesion',
            field=models.CharField(choices=[('Fotografo', 'Fotografo'), ('Programador', 'Programador'), ('Profesor particular', 'Profesor particular')], max_length=30),
        ),
    ]
