# Generated by Django 2.2 on 2019-04-30 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagweb', '0008_auto_20190430_0752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesion',
            options={'verbose_name': 'Profesion', 'verbose_name_plural': 'Profesiones'},
        ),
    ]
