# Generated by Django 2.2 on 2019-04-30 12:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pagweb', '0009_auto_20190430_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
