# Generated by Django 2.2 on 2019-04-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagweb', '0010_freelancer_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='created',
        ),
        migrations.AddField(
            model_name='profesion',
            name='imagen_chica',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='profesion',
            name='imagen_grande',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
